export { Layout } from "./Layout/Layout";
export { MainPage } from "./MainPage/MainPage";
export { CartPage } from "./CartPage/CartPage";
export { ProductListPage } from "./ProductListPage/ProductListPage";
export { ProductPage } from "./ProductPage/ProductPage";
export { OrderingPage } from "./OrderingPage/OrderingPage";
export { EndingOrderPage } from "./EndingOrderPage/EndingOrderPage";
export { CatalogPage } from "./CatalogPage/CatalogPage";
export { SearchPage } from "./SearchPage/SearchPage";
